#ApiHistogramBundle
api_histogram:
    connection: default
    schema_name: histogram
    sites:
        usd_fare:
            name: USD Fare
            url: http://apilayer.net/api/live?access_key=df4be435670ab4d7aaab0ae620458a55&currencies=USD,AUD,CAD,PLN,MXN&format=1
            formatter: ApiHistogram\ApiHistogramBundle\Cleaners\CurrencyCleaner
            database:
                table_name: currency
                create_table: true
        apple_stock:
            name: Apple Stock
            url: http://finance.yahoo.com/webservice/v1/symbols/AAPL/quote?format=json
            formatter: ApiHistogram\ApiHistogramBundle\Cleaners\YahooStockCleaner
            database:
                table_name: apple_stock
                create_table: true