app:
    resource: "@AppBundle/Controller/"
    type:     annotation

qcharts_api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix: /qcharts

qcharts_front:
    resource: "@FrontendBundle/Resources/config/routing.yml"
    prefix: /qcharts

fos_user_login:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"